### ISSUE TITLE
About add line highlight background

### ISSUE THREAD

**Issue by black-black-cat** [carakan/new-railscasts-vscode#1]
Hey buddy, Thank you for your very nice theme.

![dd](https://user-images.githubusercontent.com/15521864/64663111-509d5700-d47d-11e9-884a-24d70c431791.png)

The `lineHighlight` in `tokenColors` is failed. Should  color `#333435` be used as a line highlight?

**Comment by carakan** [comment]
Good catch! maybe those settings are deprecated `background` and `lineHighlight` so I'll delete in the next version and move to the `colors` section.
